name: address-parser
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi>=0.104.0
  - uvicorn>=0.24.0
  - pydantic>=2.5.0
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - aiofiles>=23.2.0
  - pip
  - pip:
    - mcp>=0.1.0
    - anthropic>=1.9.0
    - openai>=1.82.0
    - pydantic-settings>=2.1.0
    - structlog>=23.2.0
    - python-dotenv>=1.0.0
    - pytest-mock>=3.12.0
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.0.0